### ISSUE TITLE
move some hyperlinks to references?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/fingerprinting-guidance#19]
The doc has many hyperlinks to external docs; should some (or most) be actual references?

**Comment by npdoty** [comment]
I'm not actually sure what the conventions are for the use of references vs. plain-old hyperlinks. I'm happy to make that change. It would be great if there were an explanation somewhere so I had some guidelines for what should be a Reference.

**Comment by npdoty** [comment]
I've added a lot more to references rather than plain hyperlinks, especially where I can link to particular definitions in other specs, or when citing research inline. 

There are still plenty of hyperlinks in the research section where I'm just pointing to other places to read, and in some cases I have both hyperlinks and a [[reference]]. If there are accepted conventions on how to handle these, or pull requests to improve the consistency, I'd welcome them.

**Comment by npdoty** [comment]
We are closing for now. @samuelweiler if you have suggestions on the conventions for links vs references and want to open another issue or PR, just let me know.

**Comment by npdoty** [comment]
I also moved all the references to be "informative", rather than a mix of "informative" and "normative". I don't think for this Note that references need to be normative as no one is implementing this as a spec, it's just guidance for spec authors and implementers.
