### ISSUE TITLE
Role of prompting as mitigation

### ISSUE THREAD

**Issue by jasonanovak** [w3c/fingerprinting-guidance#21]
In the vein of #20, it seems worthwhile to add a suggestion to consider adding prompting as a mitigation if no other fingerprinting mitigation can be implemented.

**Comment by npdoty** [comment]
Re: #20 and #21: "availability", listed as one of the severity factors in evaluating fingerprinting surface, notes that characteristics available only after a permission prompt are less severe than those available to the drive-by Web. I think it's better to have it as a severity/mitigation rather than part of the definition itself, as it still might be part of browser fingerprinting, it's just less likely to be a severe problem. In terms of mitigation, I plan to add an example to BP 1 on limiting severity of new fingerprinting surface to discuss permission prompts as one possibility (though probably more of a last resort), or making that part of splitting up that best practice into a few distinct suggestions.

**Comment by npdoty** [comment]
See http://w3c.github.io/fingerprinting-guidance/#narrow-scope-availability for a best practice noting permission gating as one mitigation, with example
