### ISSUE TITLE
Predictive text and complete loss of privacy

### ISSUE THREAD

**Issue by noloader** [w3c/fingerprinting-guidance#8]
Here's an example of a complete loss of privacy due to the browser's willingness to allow data to be egressed via predictive text. There's no fingerprinting required.

In the example below, I **_almost**_ made online reservation for a hotel room. I competed the form, but then had second thoughts because of the endless stream of spam that results from providing an email address. I **_closed**_ the browser window **_before**_ submitting the form.

I **_thought**_ my data stayed within my security boundary, but within a day or two, the emails started arriving. It seems my data was egressed without my knowledge or consent. It resulted in the endless stream of spam I was trying to avoid. Also notice the ad says _"We noticed you were on our site..."_.

---

![hotel-ads](https://cloud.githubusercontent.com/assets/3538226/12238091/3f026bcc-b850-11e5-824a-16406b493690.png)

**Comment by npdoty** [comment]
As you note, this is a privacy issue that we wouldn't typically call fingerprinting. Specifically, data you enter into a form might be recorded by a site even if the form wasn't submitted.

I'm not aware of easy ways to provide transparency or control over when information is shared with a server, but thoughts on that topic would be welcome on the Privacy Interest Group mailing list: public-privacy@w3.org. I'm closing this issue for now as it doesn't seem to be in scope for the fingerprinting-guidance doc.

**Comment by contentprovider** [comment]
Is there a missing theoretical construct here?  TLD: is it not public.. Our makers work was public: man's work is private.  Everything was public, law divided public (into protected private w/remainder public) those seeking to protect their personal power and wealth by rule of law, (enclosure acts of 1650 et al.) sought to make themselves sovereign and everyone else public.   Privacy is about personal sovereignty; are we born sovereigns?  Seems sovereignty is the anti thesis to the tool of the wealthy and powerful known as the nation state.  The nation state divided the populations of the globe into parts and the rulers of the individual parts used, propaganda, social morality, law and gated access to information in order to shape the morals and cultures of the peoples that populated those nation states..     So what is the distinction between inanimate private and animate sovereign?

**Comment by maryroseMXXXVI** [comment]
USA is to far and here I tried to ask somebody who knows or have a kind of similarity issue like me coz I've seen lot of I.t education school in here in the Philippines but none of them know s how to help me that's why I make it public so anyone who would know me as adobe I.t manager and senior software engineer can help me for guidance

**Comment by ninetyfivenorth** [comment]
![super-8-meth-coffee_meme_ninetyfivenorth](https://user-images.githubusercontent.com/31463232/46430454-f6e1c800-c716-11e8-9220-da025563f7d2.png)

**Comment by Asainegams** [comment]
(Tha'"ni"phon) thana lions
