### ISSUE TITLE
Reconcile TAG feedback

### ISSUE THREAD

**Issue by slightlyoff** [w3c/fingerprinting-guidance#9]
Hey all,

Apologies for not highlighting our feedback in your repo more directly last year. The TAG has spent some time talking about the draft as it stands today and we've come up with some feedback we'd love to discuss: https://github.com/w3ctag/spec-reviews/issues/38#issuecomment-140752032

/cc @plinss @torgo

**Comment by npdoty** [comment]
Chatted briefly at today's TAG call, but couldn't get direct feedback from @slightlyoff. @torgo will help us follow up.

My notes:
- more examples agreed to be useful in making it actionable and useful for spec authors
- local state is definitely related to the Clear Site Data spec (an API used by sites to invoke clearing of data), but also something that needs to be highlighted so that browsers can do it. unclear whether this will ultimately remain in this document or move elsewhere
- I think best practices for reducing entropy fits with the "reasonable measures" suggested by the TAG finding, but need more input to understand how to respond to Alex's feedback on BP 4,5

**Comment by npdoty** [comment]
I think I've got more precise feedback from the TAG via the comments after their recent f2f meeting. See issues: #6, #12, #13.

I'll close this umbrella issue unless there are other TAG comments that aren't covered by those.
